/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tu_darmstadt.cs.encrypto.aby;

public class Circuit {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Circuit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Circuit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AbyJNI.delete_Circuit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void init() {
    AbyJNI.Circuit_init(swigCPtr, this);
  }

  public void cleanup() {
    AbyJNI.Circuit_cleanup(swigCPtr, this);
  }

  public void reset() {
    AbyJNI.Circuit_reset(swigCPtr, this);
  }

  public long getShareBitLen() {
    return AbyJNI.Circuit_getShareBitLen(swigCPtr, this);
  }

  public long getMaxDepth() {
    return AbyJNI.Circuit_getMaxDepth(swigCPtr, this);
  }

  public SWIGTYPE_p_std__dequeT_unsigned_int_t getLocalQueueOnLvl(long lvl) {
    return new SWIGTYPE_p_std__dequeT_unsigned_int_t(AbyJNI.Circuit_getLocalQueueOnLvl(swigCPtr, this, lvl), true);
  }

  public SWIGTYPE_p_std__dequeT_unsigned_int_t getInteractiveQueueOnLvl(long lvl) {
    return new SWIGTYPE_p_std__dequeT_unsigned_int_t(AbyJNI.Circuit_getInteractiveQueueOnLvl(swigCPtr, this, lvl), true);
  }

  public void printInteractiveQueues() {
    AbyJNI.Circuit_printInteractiveQueues(swigCPtr, this);
  }

  public long getNumLocalLayers() {
    return AbyJNI.Circuit_getNumLocalLayers(swigCPtr, this);
  }

  public long getNumInteractiveLayers() {
    return AbyJNI.Circuit_getNumInteractiveLayers(swigCPtr, this);
  }

  public long getNumInputBitsForParty(Role party) {
    return AbyJNI.Circuit_getNumInputBitsForParty(swigCPtr, this, party.swigValue());
  }

  public long getNumOutputBitsForParty(Role party) {
    return AbyJNI.Circuit_getNumOutputBitsForParty(swigCPtr, this, party.swigValue());
  }

  public SWIGTYPE_p_std__dequeT_unsigned_int_t getInputGatesForParty(Role party) {
    return new SWIGTYPE_p_std__dequeT_unsigned_int_t(AbyJNI.Circuit_getInputGatesForParty(swigCPtr, this, party.swigValue()), true);
  }

  public SWIGTYPE_p_std__dequeT_unsigned_int_t getOutputGatesForParty(Role party) {
    return new SWIGTYPE_p_std__dequeT_unsigned_int_t(AbyJNI.Circuit_getOutputGatesForParty(swigCPtr, this, party.swigValue()), true);
  }

  public SharingType getContext() {
    return SharingType.swigToEnum(AbyJNI.Circuit_getContext(swigCPtr, this));
  }

  public long getNumGates() {
    return AbyJNI.Circuit_getNumGates(swigCPtr, this);
  }

  public SWIGTYPE_p_gate_specific getGateSpecificOutput(long gateid) {
    return new SWIGTYPE_p_gate_specific(AbyJNI.Circuit_getGateSpecificOutput(swigCPtr, this, gateid), true);
  }

  public SWIGTYPE_p_unsigned_long_long getOutputGateValue(long gateid) {
    long cPtr = AbyJNI.Circuit_getOutputGateValue__SWIG_0(swigCPtr, this, gateid);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public long getOutputGateValue(long gateid, SWIGTYPE_p_p_unsigned_long_long outval) {
    return AbyJNI.Circuit_getOutputGateValue__SWIG_1(swigCPtr, this, gateid, SWIGTYPE_p_p_unsigned_long_long.getCPtr(outval));
  }

  public long getNumVals(long gateid) {
    return AbyJNI.Circuit_getNumVals(swigCPtr, this, gateid);
  }

  public Share putCONSGate(java.math.BigInteger val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putCONSGate__SWIG_0(swigCPtr, this, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putCONSGate(SWIGTYPE_p_unsigned_int val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putCONSGate__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putCONSGate(SWIGTYPE_p_unsigned_char val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putCONSGate__SWIG_2(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDCONSGate(long nvals, java.math.BigInteger val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSIMDCONSGate__SWIG_0(swigCPtr, this, nvals, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDCONSGate(long nvals, SWIGTYPE_p_unsigned_int val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSIMDCONSGate__SWIG_1(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_int.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDCONSGate(long nvals, SWIGTYPE_p_unsigned_char val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSIMDCONSGate__SWIG_2(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_char.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public long putConstantGate(java.math.BigInteger val, long nvals) {
    return AbyJNI.Circuit_putConstantGate__SWIG_0(swigCPtr, this, val, nvals);
  }

  public long putConstantGate(java.math.BigInteger val) {
    return AbyJNI.Circuit_putConstantGate__SWIG_1(swigCPtr, this, val);
  }

  public Share putINGate(java.math.BigInteger val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putINGate__SWIG_0(swigCPtr, this, val, bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putINGate(long val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putINGate__SWIG_1(swigCPtr, this, val, bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putINGate(int val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putINGate__SWIG_2(swigCPtr, this, val, bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putINGate(short val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putINGate__SWIG_3(swigCPtr, this, val, bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putINGate(SWIGTYPE_p_unsigned_long_long val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putINGate__SWIG_4(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(val), bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putINGate(SWIGTYPE_p_unsigned_int val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putINGate__SWIG_5(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(val), bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putINGate(SWIGTYPE_p_unsigned_short val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putINGate__SWIG_6(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(val), bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putINGate(SWIGTYPE_p_unsigned_char val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putINGate__SWIG_7(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(val), bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putDummyINGate(long bitlen) {
    long cPtr = AbyJNI.Circuit_putDummyINGate(swigCPtr, this, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDINGate(long nvals, java.math.BigInteger val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putSIMDINGate__SWIG_0(swigCPtr, this, nvals, val, bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDINGate(long nvals, long val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putSIMDINGate__SWIG_1(swigCPtr, this, nvals, val, bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDINGate(long nvals, int val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putSIMDINGate__SWIG_2(swigCPtr, this, nvals, val, bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDINGate(long nvals, short val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putSIMDINGate__SWIG_3(swigCPtr, this, nvals, val, bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDINGate(long nvals, SWIGTYPE_p_unsigned_long_long val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putSIMDINGate__SWIG_4(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_long_long.getCPtr(val), bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDINGate(long nvals, SWIGTYPE_p_unsigned_int val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putSIMDINGate__SWIG_5(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_int.getCPtr(val), bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDINGate(long nvals, SWIGTYPE_p_unsigned_short val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putSIMDINGate__SWIG_6(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_short.getCPtr(val), bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDINGate(long nvals, SWIGTYPE_p_unsigned_char val, long bitlen, Role role) {
    long cPtr = AbyJNI.Circuit_putSIMDINGate__SWIG_7(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_char.getCPtr(val), bitlen, role.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putDummySIMDINGate(long nvals, long bitlen) {
    long cPtr = AbyJNI.Circuit_putDummySIMDINGate(swigCPtr, this, nvals, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedINGate(java.math.BigInteger val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedINGate__SWIG_0(swigCPtr, this, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedINGate(long val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedINGate__SWIG_1(swigCPtr, this, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedINGate(int val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedINGate__SWIG_2(swigCPtr, this, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedINGate(short val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedINGate__SWIG_3(swigCPtr, this, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedINGate(SWIGTYPE_p_unsigned_long_long val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedINGate__SWIG_4(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedINGate(SWIGTYPE_p_unsigned_int val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedINGate__SWIG_5(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedINGate(SWIGTYPE_p_unsigned_short val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedINGate__SWIG_6(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedINGate(SWIGTYPE_p_unsigned_char val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedINGate__SWIG_7(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedSIMDINGate(long nvals, java.math.BigInteger val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedSIMDINGate__SWIG_0(swigCPtr, this, nvals, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedSIMDINGate(long nvals, long val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedSIMDINGate__SWIG_1(swigCPtr, this, nvals, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedSIMDINGate(long nvals, int val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedSIMDINGate__SWIG_2(swigCPtr, this, nvals, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedSIMDINGate(long nvals, short val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedSIMDINGate__SWIG_3(swigCPtr, this, nvals, val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedSIMDINGate(long nvals, SWIGTYPE_p_unsigned_long_long val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedSIMDINGate__SWIG_4(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_long_long.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedSIMDINGate(long nvals, SWIGTYPE_p_unsigned_int val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedSIMDINGate__SWIG_5(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_int.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedSIMDINGate(long nvals, SWIGTYPE_p_unsigned_short val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedSIMDINGate__SWIG_6(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_short.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedSIMDINGate(long nvals, SWIGTYPE_p_unsigned_char val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSharedSIMDINGate__SWIG_7(swigCPtr, this, nvals, SWIGTYPE_p_unsigned_char.getCPtr(val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putADDGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putADDGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSUBGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putSUBGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putANDGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putANDGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putXORGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putXORGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putMULGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putMULGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putGTGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putGTGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putEQGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putEQGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putMUXGate(Share ina, Share inb, Share sel) {
    long cPtr = AbyJNI.Circuit_putMUXGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb, Share.getCPtr(sel), sel);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putUniversalGate(Share ina, Share inb, long op_id) {
    long cPtr = AbyJNI.Circuit_putUniversalGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb, op_id);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putY2BGate(Share ina) {
    long cPtr = AbyJNI.Circuit_putY2BGate(swigCPtr, this, Share.getCPtr(ina), ina);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putB2AGate(Share ina) {
    long cPtr = AbyJNI.Circuit_putB2AGate(swigCPtr, this, Share.getCPtr(ina), ina);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putB2YGate(Share ina) {
    long cPtr = AbyJNI.Circuit_putB2YGate(swigCPtr, this, Share.getCPtr(ina), ina);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putA2YGate(Share ina) {
    long cPtr = AbyJNI.Circuit_putA2YGate(swigCPtr, this, Share.getCPtr(ina), ina);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putY2AGate(Share ina, Circuit boolsharingcircuit) {
    long cPtr = AbyJNI.Circuit_putY2AGate(swigCPtr, this, Share.getCPtr(ina), ina, Circuit.getCPtr(boolsharingcircuit), boolsharingcircuit);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putA2BGate(Share ina, Circuit yaosharingcircuit) {
    long cPtr = AbyJNI.Circuit_putA2BGate(swigCPtr, this, Share.getCPtr(ina), ina, Circuit.getCPtr(yaosharingcircuit), yaosharingcircuit);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putANDVecGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putANDVecGate(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putCallbackGate(Share in, long rounds, SWIGTYPE_p_f_p_GATE_p_void__void callback, SWIGTYPE_p_void infos, long nvals) {
    long cPtr = AbyJNI.Circuit_putCallbackGate(swigCPtr, this, Share.getCPtr(in), in, rounds, SWIGTYPE_p_f_p_GATE_p_void__void.getCPtr(callback), SWIGTYPE_p_void.getCPtr(infos), nvals);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putTruthTableGate(Share in, SWIGTYPE_p_unsigned_long_long ttable) {
    long cPtr = AbyJNI.Circuit_putTruthTableGate(swigCPtr, this, Share.getCPtr(in), in, SWIGTYPE_p_unsigned_long_long.getCPtr(ttable));
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putTruthTableMultiOutputGate(Share in, long out_bits, SWIGTYPE_p_unsigned_long_long ttable) {
    long cPtr = AbyJNI.Circuit_putTruthTableMultiOutputGate(swigCPtr, this, Share.getCPtr(in), in, out_bits, SWIGTYPE_p_unsigned_long_long.getCPtr(ttable));
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putPrintValueGate(Share in, String helpstr) {
    long cPtr = AbyJNI.Circuit_putPrintValueGate(swigCPtr, this, Share.getCPtr(in), in, helpstr);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putAssertGate(Share in, SWIGTYPE_p_unsigned_long_long assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putAssertGate__SWIG_0(swigCPtr, this, Share.getCPtr(in), in, SWIGTYPE_p_unsigned_long_long.getCPtr(assert_val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putAssertGate(Share in, SWIGTYPE_p_unsigned_int assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putAssertGate__SWIG_1(swigCPtr, this, Share.getCPtr(in), in, SWIGTYPE_p_unsigned_int.getCPtr(assert_val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putAssertGate(Share in, SWIGTYPE_p_unsigned_short assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putAssertGate__SWIG_2(swigCPtr, this, Share.getCPtr(in), in, SWIGTYPE_p_unsigned_short.getCPtr(assert_val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putAssertGate(Share in, SWIGTYPE_p_unsigned_char assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putAssertGate__SWIG_3(swigCPtr, this, Share.getCPtr(in), in, SWIGTYPE_p_unsigned_char.getCPtr(assert_val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putAssertGate(Share in, java.math.BigInteger assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putAssertGate__SWIG_4(swigCPtr, this, Share.getCPtr(in), in, assert_val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putAssertGate(Share in, long assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putAssertGate__SWIG_5(swigCPtr, this, Share.getCPtr(in), in, assert_val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putAssertGate(Share in, int assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putAssertGate__SWIG_6(swigCPtr, this, Share.getCPtr(in), in, assert_val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putAssertGate(Share in, short assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putAssertGate__SWIG_7(swigCPtr, this, Share.getCPtr(in), in, assert_val, bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDAssertGate(Share in, long nvals, SWIGTYPE_p_unsigned_long_long assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSIMDAssertGate__SWIG_0(swigCPtr, this, Share.getCPtr(in), in, nvals, SWIGTYPE_p_unsigned_long_long.getCPtr(assert_val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDAssertGate(Share in, long nvals, SWIGTYPE_p_unsigned_int assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSIMDAssertGate__SWIG_1(swigCPtr, this, Share.getCPtr(in), in, nvals, SWIGTYPE_p_unsigned_int.getCPtr(assert_val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDAssertGate(Share in, long nvals, SWIGTYPE_p_unsigned_short assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSIMDAssertGate__SWIG_2(swigCPtr, this, Share.getCPtr(in), in, nvals, SWIGTYPE_p_unsigned_short.getCPtr(assert_val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSIMDAssertGate(Share in, long nvals, SWIGTYPE_p_unsigned_char assert_val, long bitlen) {
    long cPtr = AbyJNI.Circuit_putSIMDAssertGate__SWIG_3(swigCPtr, this, Share.getCPtr(in), in, nvals, SWIGTYPE_p_unsigned_char.getCPtr(assert_val), bitlen);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putCombinerGate(Share input) {
    long cPtr = AbyJNI.Circuit_putCombinerGate__SWIG_0(swigCPtr, this, Share.getCPtr(input), input);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putCombinerGate(Share ina, Share inb) {
    long cPtr = AbyJNI.Circuit_putCombinerGate__SWIG_1(swigCPtr, this, Share.getCPtr(ina), ina, Share.getCPtr(inb), inb);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSplitterGate(Share input) {
    long cPtr = AbyJNI.Circuit_putSplitterGate__SWIG_0(swigCPtr, this, Share.getCPtr(input), input);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putRepeaterGate(long nvals, Share input) {
    long cPtr = AbyJNI.Circuit_putRepeaterGate__SWIG_0(swigCPtr, this, nvals, Share.getCPtr(input), input);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSubsetGate(Share input, SWIGTYPE_p_unsigned_int posids, long nvals_out, boolean copy_posids) {
    long cPtr = AbyJNI.Circuit_putSubsetGate__SWIG_0(swigCPtr, this, Share.getCPtr(input), input, SWIGTYPE_p_unsigned_int.getCPtr(posids), nvals_out, copy_posids);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSubsetGate(Share input, SWIGTYPE_p_unsigned_int posids, long nvals_out) {
    long cPtr = AbyJNI.Circuit_putSubsetGate__SWIG_1(swigCPtr, this, Share.getCPtr(input), input, SWIGTYPE_p_unsigned_int.getCPtr(posids), nvals_out);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putCombineAtPosGate(Share input, long pos) {
    long cPtr = AbyJNI.Circuit_putCombineAtPosGate__SWIG_0(swigCPtr, this, Share.getCPtr(input), input, pos);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putPermutationGate(Share input, SWIGTYPE_p_unsigned_int positions) {
    long cPtr = AbyJNI.Circuit_putPermutationGate__SWIG_0(swigCPtr, this, Share.getCPtr(input), input, SWIGTYPE_p_unsigned_int.getCPtr(positions));
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public long putRepeaterGate(long input, long nvals) {
    return AbyJNI.Circuit_putRepeaterGate__SWIG_1(swigCPtr, this, input, nvals);
  }

  public long putCombinerGate(SWIGTYPE_p_std__vectorT_unsigned_int_t input) {
    return AbyJNI.Circuit_putCombinerGate__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(input));
  }

  public long putCombineAtPosGate(SWIGTYPE_p_std__vectorT_unsigned_int_t input, long pos) {
    return AbyJNI.Circuit_putCombineAtPosGate__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(input), pos);
  }

  public long putSubsetGate(long input, SWIGTYPE_p_unsigned_int posids, long nvals_out, boolean copy_posids) {
    return AbyJNI.Circuit_putSubsetGate__SWIG_2(swigCPtr, this, input, SWIGTYPE_p_unsigned_int.getCPtr(posids), nvals_out, copy_posids);
  }

  public long putSubsetGate(long input, SWIGTYPE_p_unsigned_int posids, long nvals_out) {
    return AbyJNI.Circuit_putSubsetGate__SWIG_3(swigCPtr, this, input, SWIGTYPE_p_unsigned_int.getCPtr(posids), nvals_out);
  }

  public long putPermutationGate(SWIGTYPE_p_std__vectorT_unsigned_int_t input, SWIGTYPE_p_unsigned_int positions) {
    return AbyJNI.Circuit_putPermutationGate__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(input), SWIGTYPE_p_unsigned_int.getCPtr(positions));
  }

  public SWIGTYPE_p_std__vectorT_unsigned_int_t putSplitterGate(long input) {
    return new SWIGTYPE_p_std__vectorT_unsigned_int_t(AbyJNI.Circuit_putSplitterGate__SWIG_1(swigCPtr, this, input), true);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_int_t putSplitterGate(long input, SWIGTYPE_p_std__vectorT_unsigned_int_t new_nvals) {
    return new SWIGTYPE_p_std__vectorT_unsigned_int_t(AbyJNI.Circuit_putSplitterGate__SWIG_2(swigCPtr, this, input, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(new_nvals)), true);
  }

  public Share putOUTGate(Share parent, Role dst) {
    long cPtr = AbyJNI.Circuit_putOUTGate(swigCPtr, this, Share.getCPtr(parent), parent, dst.swigValue());
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public Share putSharedOUTGate(Share parent) {
    long cPtr = AbyJNI.Circuit_putSharedOUTGate(swigCPtr, this, Share.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new Share(cPtr, false);
  }

  public long putINVGate(long parentid) {
    return AbyJNI.Circuit_putINVGate(swigCPtr, this, parentid);
  }

  public CircuitType getCircuitType() {
    return CircuitType.swigToEnum(AbyJNI.Circuit_getCircuitType(swigCPtr, this));
  }

  public int getNumCombGates() {
    return AbyJNI.Circuit_getNumCombGates(swigCPtr, this);
  }

  public int getNumStructCombGates() {
    return AbyJNI.Circuit_getNumStructCombGates(swigCPtr, this);
  }

  public int getNumPermGates() {
    return AbyJNI.Circuit_getNumPermGates(swigCPtr, this);
  }

  public int getNumSubsetGates() {
    return AbyJNI.Circuit_getNumSubsetGates(swigCPtr, this);
  }

  public int getNumSplitGates() {
    return AbyJNI.Circuit_getNumSplitGates(swigCPtr, this);
  }

  public Role getRole() {
    return Role.swigToEnum(AbyJNI.Circuit_getRole(swigCPtr, this));
  }

  public void exportCircuitInBristolFormat(Share ingates_client, Share ingates_server, Share outgates, String filename) {
    AbyJNI.Circuit_exportCircuitInBristolFormat(swigCPtr, this, Share.getCPtr(ingates_client), ingates_client, Share.getCPtr(ingates_server), ingates_server, Share.getCPtr(outgates), outgates, filename);
  }

}
