/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tu_darmstadt.cs.encrypto.aby;

public enum MultiplicationTripleGenerationAlgorithm {
  MT_OT(0),
  MT_PAILLIER(1),
  MT_DGK(2),
  MT_LAST(3);

  public final int swigValue() {
    return swigValue;
  }

  public static MultiplicationTripleGenerationAlgorithm swigToEnum(int swigValue) {
    MultiplicationTripleGenerationAlgorithm[] swigValues = MultiplicationTripleGenerationAlgorithm.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (MultiplicationTripleGenerationAlgorithm swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + MultiplicationTripleGenerationAlgorithm.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private MultiplicationTripleGenerationAlgorithm() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private MultiplicationTripleGenerationAlgorithm(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private MultiplicationTripleGenerationAlgorithm(MultiplicationTripleGenerationAlgorithm swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

