/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tu_darmstadt.cs.encrypto.aby;

public enum Phase {
  P_TOTAL,
  P_INIT,
  P_CIRCUIT,
  P_NETWORK,
  P_BASE_OT,
  P_SETUP,
  P_OT_EXT,
  P_GARBLE,
  P_ONLINE,
  P_FIRST(P_TOTAL),
  P_LAST(P_ONLINE);

  public final int swigValue() {
    return swigValue;
  }

  public static Phase swigToEnum(int swigValue) {
    Phase[] swigValues = Phase.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Phase swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Phase.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Phase() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Phase(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Phase(Phase swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

