/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tu_darmstadt.cs.encrypto.aby;

public class SecurityLevel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SecurityLevel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SecurityLevel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public void setStatbits(long value) {
    AbyJNI.SecurityLevel_statbits_set(swigCPtr, this, value);
  }

  public long getStatbits() {
    return AbyJNI.SecurityLevel_statbits_get(swigCPtr, this);
  }

  public void setSymbits(long value) {
    AbyJNI.SecurityLevel_symbits_set(swigCPtr, this, value);
  }

  public long getSymbits() {
    return AbyJNI.SecurityLevel_symbits_get(swigCPtr, this);
  }

  public void setIfcbits(long value) {
    AbyJNI.SecurityLevel_ifcbits_set(swigCPtr, this, value);
  }

  public long getIfcbits() {
    return AbyJNI.SecurityLevel_ifcbits_get(swigCPtr, this);
  }

  public SecurityLevel() {
    this(AbyJNI.new_SecurityLevel(), true);
  }

}
