/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tu_darmstadt.cs.encrypto.aby;

public enum SharingType {
  S_BOOL(0),
  S_YAO(1),
  S_ARITH(2),
  S_YAO_REV(3),
  S_SPLUT(4);

  public final int swigValue() {
    return swigValue;
  }

  public static SharingType swigToEnum(int swigValue) {
    SharingType[] swigValues = SharingType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SharingType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SharingType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SharingType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SharingType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SharingType(SharingType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

