/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tu_darmstadt.cs.encrypto.aby;

public class UInt32Vector extends java.util.AbstractList<Long> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UInt32Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UInt32Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public UInt32Vector(long[] initialElements) {
    this();
    reserve(initialElements.length);

    for (long element : initialElements) {
      add(element);
    }
  }

  public UInt32Vector(Iterable<Long> initialElements) {
    this();
    for (long element : initialElements) {
      add(element);
    }
  }

  public Long get(int index) {
    return doGet(index);
  }

  public Long set(int index, Long e) {
    return doSet(index, e);
  }

  public boolean add(Long e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Long e) {
    modCount++;
    doAdd(index, e);
  }

  public Long remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public UInt32Vector() {
    this(AbyJNI.new_UInt32Vector__SWIG_0(), true);
  }

  public UInt32Vector(UInt32Vector other) {
    this(AbyJNI.new_UInt32Vector__SWIG_1(UInt32Vector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AbyJNI.UInt32Vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AbyJNI.UInt32Vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AbyJNI.UInt32Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AbyJNI.UInt32Vector_clear(swigCPtr, this);
  }

  public UInt32Vector(int count, long value) {
    this(AbyJNI.new_UInt32Vector__SWIG_2(count, value), true);
  }

  private int doSize() {
    return AbyJNI.UInt32Vector_doSize(swigCPtr, this);
  }

  private void doAdd(long x) {
    AbyJNI.UInt32Vector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, long x) {
    AbyJNI.UInt32Vector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private long doRemove(int index) {
    return AbyJNI.UInt32Vector_doRemove(swigCPtr, this, index);
  }

  private long doGet(int index) {
    return AbyJNI.UInt32Vector_doGet(swigCPtr, this, index);
  }

  private long doSet(int index, long val) {
    return AbyJNI.UInt32Vector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AbyJNI.UInt32Vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
