name: CI

on:
  push:
  pull_request:
  release:
    types: [ published ]

env:
  JDK_DISTRIBUTION: zulu
  JDK_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}
      - name: Generate classes and native binaries
        uses: gradle/gradle-build-action@v1
        with:
          arguments: classes check -x test
      - name: Upload generated files for other jobs
        uses: actions/upload-artifact@v2
        with:
          name: ClassesAndResources
          path: |
            build/classes
            build/resources

  test:
    name: test (${{ matrix.os }}, JDK ${{ matrix.java }})
    needs: build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-18.04
          - ubuntu-20.04
        java:
          - 11
          # - 14

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ matrix.java }}
      - name: Download generated files
        uses: actions/download-artifact@v2
        with:
          name: ClassesAndResources
          path: build
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          arguments: -x classes test --tests=*AbyTest.constantGate

  publish:
    needs: test
    if: github.event_name == 'release'

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}
      - name: Download generated files
        uses: actions/download-artifact@v2
        with:
          name: ClassesAndResources
          path: build
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: -x classes publish
