name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: build (${{ matrix.os }}, JDK ${{ matrix.java }})

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
        java:
          - 11
          # - 14

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Install Docker
        if: runner.os == 'macOS'
        run: |
          brew install docker docker-machine
          docker-machine create --driver virtualbox default
          docker-machine env default
          docker-machine env default | head -n 4 | cut -f 2- -d ' ' | sed 's/"//g' >> $GITHUB_ENV
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check test --tests=*AbyTest.constantGate
